### ISSUE TITLE
Switches, Range Slider, Select and Radio buttons in Forms page not working in Edge/FireFox/Safari

### ISSUE THREAD

**Issue by dbaba** [frandiox/vue-onsenui-kitchensink#2]
I found some formes worked only in Chrome at the [preview page](https://frandiox.github.io/vue-onsenui-kitchensink/).
Does OnsenUI support desktop Edge/FireFox/Safari? I'm new to OnsenUI and don't know if the issue comes from OnsenUI or this project stuff.

- Switches
  - enable/disable animation did work
  - the switch labels didn't change (always "Switch (on)" and "Enabled switch")
![switches](https://cloud.githubusercontent.com/assets/1858156/25221150/0ab190c4-25ef-11e7-8fc7-e3ff5e02025b.jpg)

- Range Slider
  - always showed 25 when I moved the slider
![edge-safar-range](https://cloud.githubusercontent.com/assets/1858156/25221181/1b910cb2-25ef-11e7-84d6-91a9b7d5788e.jpg)
  - Slider bar not colored in FireFox
![firefox-range](https://cloud.githubusercontent.com/assets/1858156/25221185/22106362-25ef-11e7-95e6-7232dbdadbc3.jpg)

- Select
  - The sentence never changed (always "Vue is awesome")
- Radio Buttons
  - all items were checked! and the bottom message never changed
![select-radio](https://cloud.githubusercontent.com/assets/1858156/25222066/4fc68482-25f2-11e7-888b-9fcde6683045.jpg)

Tested browsers:

1. Microsoft Edge 38.14393.1066.0 (Windows 10 Version 10.0.14393)
1. FireFox 53.0 (macOS 10.12.4)
1. Safari 10.1 (macOS 10.12.4)
1. Chrome 57.0.2987.133 (macOS 10.12.4)

**Comment by frandiox** [comment]
@dbaba Hey! Thanks for reporting. It's related to this repo stuff :sweat_smile: 
I fixed that issue a few days ago but actually forgot to upload the new release to this repo. I'll do it now :)

You can have a look at the [interactive tutorial](http://tutorial.onsen.io/?framework=vue&category=reference&module=input) to see a working version. It automatically fetches the latest versions.

**Comment by dbaba** [comment]
Thanks!
