### ISSUE TITLE
Postcss loader plugins return null 

### ISSUE THREAD

**Issue by anthonykhy** [frandiox/vue-onsenui-kitchensink#3]
I just run yarn and npm install and it returns the below error
    ERROR in ./~/css-loader?{"importLoaders":1}!./~/postcss-loader?{"plugins":[null,null,null]}!./~/onsenui/css-components-src/src/onsen-css-components.css                      
    Module not found: Error: Can't resolve './components/img/ios-search-input-icon.svg' in '/home/cabox/workspace/beerclient/node_modules/onsenui/css-components-src/src'        
     @ ./~/css-loader?{"importLoaders":1}!./~/postcss-loader?{"plugins":[null,null,null]}!./~/onsenui/css-components-src/src/onsen-css-components.css 6:90899-90952    

In webpack.config
loader: 'postcss-loader',
              options: {
                plugins: [
                  require('postcss-smart-import'),
                  require('postcss-url'),
                  require('postcss-cssnext')
                ]

**Comment by frandiox** [comment]
@anthonykhy Hmm, the plugins are listed in [`package.json`#L28](https://github.com/frandiox/vue-onsenui-kitchensink/blob/master/package.json#L28). Aren't you getting them in `node_modules` after running `yarn install`?
