### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by anthonykhy** [frandiox/vue-onsenui-kitchensink#4]
After running the yarn run dev, succeed with no error.
There is nothing to show on web with errors below:

onsenui.js:23444 Uncaught TypeError: Cannot read property 'style' of null

        _this3.content.style[side.side] = side.mode === 'split' ? side._width : 0;

**Comment by anthonykhy** [comment]
no error while updated nvm

**Comment by frandiox** [comment]
Probably related to a versioning issue. Please try with the [new repo](https://github.com/OnsenUI/vue-onsenui-kitchensink).
