### ISSUE TITLE
no-vuex: Popover stops working

### ISSUE THREAD

**Issue by rolbr** [frandiox/vue-onsenui-kitchensink#6]
Dialogs > Popover - MD Menu
Dialogs > (Toolbar) > More

These stop working when clicking outside the Popover to close.

They work fine as long as one closes them by clicking on any of the 4 options within the Popover. Once clicking on the background / shade / mask behind the Popover, the Popover will close but not open again.

Note: this occures when running the no-vuex branch locally. The [demo here on github](https://frandiox.github.io/vue-onsenui-kitchensink/) seems to show the master branch.

**Comment by frandiox** [comment]
@rolbr This is related to an update in `vue-onsenui`. I updated master branch but forgot about `no-vuex` branch. Basically, the `update` event changed to `update:propName` to make it compatible with `sync` modifier from `vue@2.3.0`.

`:visible="dialogVisible" @update="dialogVisible = $event"` should be `:visible="dialogVisible" @update:visible="dialogVisible = $event"`, or directly `:visible.sync="dialogVisible"`.

I'll try to update that branch next week.

**Comment by rolbr** [comment]
Hi @frandiox , thanks for getting back so quickly.
`:visible.sync="popoverVisible"` didn't do much for me, but 
`:visible="popoverVisible" @update:visible="popoverVisible = $event"` however works perfectly.

**Comment by frandiox** [comment]
@rolbr That's probably because you didn't update `vue` or `vue-template-compiler` dependencies :P
