### ISSUE TITLE
Carousel: swipe only works when "Chrome Dev 'Toggle Device Toolbar'" is active

### ISSUE THREAD

**Issue by rolbr** [frandiox/vue-onsenui-kitchensink#7]
In the [demo](https://frandiox.github.io/vue-onsenui-kitchensink/) one can swipe through the carousel using a mouse. Checking out and running the master branch locally (yarn run dev) this does not work. 

I need to enable the Mobile Device Toolbar (Ctrl+Shift+M) in Chrome's Dev Tools to be able to swipe through the carousel with a mouse.

Using the touch display on my Dell XPS, I can swipe through the carousel without having the Device Toolbar active, so I suspect mouse events to be ignored in favor of touch events.

Clicking on the pagination dots to change the carousel's active slide always works.

**Comment by frandiox** [comment]
Probably related to some dependency version as well. I don't have a touch display but it works fine when I do normal clicks. Please check the [new repo location](https://github.com/OnsenUI/vue-onsenui-kitchensink) of this app for more updates.
