### ISSUE TITLE
Opening the menu by swiping with a mouse does not work

### ISSUE THREAD

**Issue by rolbr** [frandiox/vue-onsenui-kitchensink#8]
In the [demo](https://frandiox.github.io/vue-onsenui-kitchensink/) one can swipe from right to left with a mouse to open the side menu. I'm unable to achieve this when running the master branch locally. Enabling 'Mobile Device Toolbar' in Chrome's Dev Tools fixes this, presumably by translating mouse events to touch events.

Possibly related: #7

**Comment by frandiox** [comment]
Same as in #7 :+1:
