### ISSUE TITLE
Home: Cards cannot be clicked

### ISSUE THREAD

**Issue by rolbr** [frandiox/vue-onsenui-kitchensink#9]
The cards ins the Home view (Pull Hook, Dialogs, Buttons...) cannot be clicked (or tapped) when checking out the master branch and running it locally. Contrary to #7, this cannot be fixed by enabling Chrome's 'Mobile Device Toolbar'.

However, moving `@click="push(page.component, page.label)` from `<v-ons-card>` to `<div .title>` enables clicking (although, of course, only on the title, not on the card).

**Comment by frandiox** [comment]
It should be fine in `vue-onsenui@2.1.0`.
